---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: topology-aware-lifecycle-manager
  namespace: openshift-operators
spec:
  channel: "4.12"
  name: topology-aware-lifecycle-manager
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: topology-aware-lifecycle-manager.v4.12.6
