---
apiVersion: v1
kind: Namespace
metadata:
  name: cephfs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-volume
  namespace: cephfs-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fc-container
        image: fedora:32
        command: ["/bin/sh", "-c"]
        args: ["tail -f /dev/null"]
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cephfs-pvc
