---
apiVersion: v1
kind: Namespace
metadata:
  name: cephfs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
  namespace: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: cephfs-pvc
spec:
  volumes:
    - name: cephfs-pvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: cephfs-pvc
