apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-net-ens1f1-netdev
  namespace: openshift-sriov-network-operator
spec:
  networkNamespace: sriov-testing
  ipam: '{ "type": "static" }'
  vlan: 309
  resourceName: sriovens1f0vf1
  trust: "on"
  capabilities: '{ "ips": true }'
