apiVersion: v1
kind: Pod
metadata:
  name: sriovpodb
  namespace: sriov-testing
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
                "name": "sriov-net-ens1f0-vfiopci",
                "mac": "20:04:0f:f1:88:02",
                "ips": ["192.168.10.11/24", "2001::11/64"]
        }
]'
spec:
  containers:
  - name: sample-container
    image: registry.redhat.io/rhel8/support-tools
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
