apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: master-profile
spec:
  additionalKernelArgs:
  - nmi_watchdog=0
  - audit=1
  - mce=off
  - processor.max_cstate=1
  - intel_idle.max_cstate=0
  - rcupdate.rcu_normal_after_boot=0
  - module_blacklist=irdma
  - iommu=pt
  - intel_iommu=on
  cpu:
    isolated: 2-19,22-39
    reserved: 0-1,20-21
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 56
      size: 1G
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
