---
apiVersion: v1
kind: Namespace
metadata:
  name: sriov-testing
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network
  namespace: openshift-sriov-network-operator
spec:
  ipam: |
    {
      "type": "dhcp"
    }
  networkNamespace: sriov-testing
  resourceName: ens7f0resspk
  vlan: 0
