apiVersion: v1
kind: Namespace
metadata:
  name: sriov-example
---
apiVersion: v1
kind: Pod
metadata:
  name: sriovpod-example
  namespace: sriov-example
  annotations:
    k8s.v1.cni.cncf.io/networks: sriovnetwork-example
spec:
  containers:
  - name: sriovpod
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep 600000& wait"]
    image: ubi8/ubi
